// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notification.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20250227170710_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notification.Domain.Entities.User.UserData", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.ToTable("user_data", (string)null);
                });

            modelBuilder.Entity("Notification.Domain.Entities.User.UserState", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TelegramUserId"));

                    b.Property<int?>("LastUserMessage")
                        .HasColumnType("integer");

                    b.Property<string>("Pages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserDataId")
                        .HasColumnType("uuid");

                    b.HasKey("TelegramUserId");

                    b.HasIndex("UserDataId")
                        .IsUnique();

                    b.ToTable("user_state", (string)null);
                });

            modelBuilder.Entity("Notification.Domain.Entities.User.UserState", b =>
                {
                    b.HasOne("Notification.Domain.Entities.User.UserData", "UserData")
                        .WithOne("UserState")
                        .HasForeignKey("Notification.Domain.Entities.User.UserState", "UserDataId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("Notification.Domain.Entities.User.UserData", b =>
                {
                    b.Navigation("UserState");
                });
#pragma warning restore 612, 618
        }
    }
}
