x-common: &common
  restart: unless-stopped

services:
  db:
    <<: *common
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    #  POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
    #  - ./postgres-data:/var/lib/postgresql/data
    container_name: db_postgresql_container
    networks:
      - app-network

  catalog-service:
    <<: *common
    build:
      context: ./CatalogService
      dockerfile: Catalog.Web/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: catalog-service
    networks:
      - app-network

  order-service:
    <<: *common
    build:
      context: ./OrderService
      dockerfile: Order.Web/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    container_name: order-service
    networks:
      - app-network

  order-processing-service:
    <<: *common
    build:
      context: ./OrderProcessingService
      dockerfile: OrderProcessingService.Web/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
    container_name: order-processing-service
    networks:
      - app-network

  zookeeper:
    <<: *common
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    <<: *common
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - app-network

  serilog_seq:
    <<: *common
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8083:80"
    container_name: serilog_seq
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
