services:
    db:
        image: postgres:16
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=test
            - POSTGRES_USER=test
            - POSTGRES_DB=catalog_service
    catalog-service:
        build: ./CatalogService
        ports:
            - "8080:8080"
        restart: unless-stopped