version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      
  db_hangfire:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./data/sqlserver:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrongPassword"

  catalog-service:
    build:
      context: ./CatalogService
      dockerfile: Catalog.Web/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  order-service:
    build:
      context: ./OrderService 
      dockerfile: Order.Web/Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
  
  order-processing-service:
    build:
      context: ./OrderProcessingService
      dockerfile: OrderProcessingService.Web/Dockerfile
    ports:
      - "8082:8082"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
    ports:
      - "9092:9092"
